/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Robot_MyRobot */

#ifndef _Included_Robot_MyRobot
#define _Included_Robot_MyRobot
#ifdef __cplusplus
extern "C" {
#endif
#undef Robot_MyRobot_delayDuration
#define Robot_MyRobot_delayDuration 200L
#undef Robot_MyRobot_screenResolutionFactor
#define Robot_MyRobot_screenResolutionFactor 0.8
/*
 * Class:     Robot_MyRobot
 * Method:    processImage
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_Robot_MyRobot_processImage__Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     Robot_MyRobot
 * Method:    processImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_Robot_MyRobot_processImage__Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

/*
 * Class:     Robot_MyRobot
 * Method:    imageCalibration
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Robot_MyRobot_imageCalibration
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
